### ISSUE TITLE
Revamp the important information page

### ISSUE THREAD

**Issue by aryapandeyy22** [swciitg/Freshers_Portal#12]
![Screenshot 2024-10-25 200112](https://github.com/user-attachments/assets/73f67a9e-900c-41ca-8c06-b109d46b0eb1)
The content should be displayed in this format

**Comment by laladwesh** [comment]
Hey @aryapandeyy22  can you assign me this

**Comment by aryapandeyy22** [comment]
assigned @laladwesh
