### ISSUE TITLE
Changes in navbar

### ISSUE THREAD

**Issue by aryapandeyy22** [swciitg/Freshers_Portal#6]
![Screenshot 2024-10-24 153130](https://github.com/user-attachments/assets/21bfa6c9-f2ce-4ea2-a04a-97990ce906cc)

for reference purposes

**Comment by ramdhankumar1425** [comment]
@aryapandeyy22 assign this to me

**Comment by aryapandeyy22** [comment]
assigning it to you @ramdhankumar1425
