### ISSUE TITLE
Implement the inter-hostel events section of the fresher's portal based on the new design

### ISSUE THREAD

**Issue by aryapandeyy22** [swciitg/Freshers_Portal#7]
![Screenshot 2024-10-24 154331](https://github.com/user-attachments/assets/006677cd-e0d9-4545-91f0-dae508ea8908)

refer to the fresher's portal for the content 
https://www.iitg.ac.in/freshers

**Comment by laladwesh** [comment]
hey @aryapandeyy22 i'll work on this

**Comment by aryapandeyy22** [comment]
assigning it to you @laladwesh
